server:
  port: 8080

spring:
  application:
    name: mentor
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mentor?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
        initializationFailTimeout: 0
        maximumPoolSize: 10
        connectionTimeout: 30000
        validationTimeout: 5000
  sql:
    init:
      mode: never  # 临时关闭
      schema-locations: classpath:schema.sql
      data-locations: classpath:iniData.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wechat:
  appid: wxd02e1d1b6906efbd
  secret: 1fd29bea30b711cdbbc5b88316a2b954

auth:
  tokenTtlDays: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

aliyun:
  oss:
    endpoint:
    accessKeyId: 
    accessKeySecret: 
    bucketName: 

